sudo: false
language: node_js
node_js:
  - '5'
  - '6'
  - '7'
  - 'lts/*'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run test
  # - npm run lint
  # - npm run test:cover
after_success:
  # - npm run coveralls
